parameters:
    oauth_client.login_success_route: oauth_client_login_success
    oauth_client.login_success_template: JumaqOAuthClientBundle:Security:login_success.html.twig
    oauth_client.login_route: fos_user_security_login