oauth_client_login_check:
    path:     /oauthclient/login-check
    defaults: { _controller: "JumaqOAuthClientBundle:Security:loginCheck" }
    methods: POST

oauth_client_login_success:
    path:     /oauthclient/login-success
    defaults: { _controller: "JumaqOAuthClientBundle:Security:loginSuccess" }
    methods: GET

