services:
    oauth.security.authentication.listener:
        class: Jumaq\Bundle\OAuthClientBundle\Security\Firewall\OAuthListener
        arguments:
            - @security.context
            - "" #oauth.security.authentication.provider, managed by the factory
            - @event_dispatcher
            - @session
        abstract: true
        public: false

    oauth.security.authentication.provider:
        class: Jumaq\Bundle\OAuthClientBundle\Security\Authentication\OAuthProvider
        arguments:
            - "" #User manager, managed by the factory
            - "%remote_api%"
            - "%remote_api.id%"
            - "%remote_api.secret%"
        public: false

